<?php

namespace Database\Seeders;

use App\Models\SubService;
use Illuminate\Database\Seeder;

class SubServicesSeeder extends Seeder
{
    public function run(): void
    {
        // Évite les doublons si le seeder est lancé plusieurs fois
        if (SubService::count() > 0) {
            $this->command->info('SubServices : données déjà existantes, seeder ignoré.');
            return;
        }

        $subServices = [

            // ──────────────────────────────────────────────────────────────────
            // Service 1 — Débarras
            // ──────────────────────────────────────────────────────────────────

            [
                'id'                => 1,
                'service_id'        => 1,
                'slug'              => 'debarras-appartement',
                'name'              => 'Débarras Appartement',
                'icon'              => '📦',
                'short_description' => 'Vidage complet ou partiel de votre appartement, du studio au T5. Intervention rapide et devis gratuit.',
                'description'       => "Notre service de débarras d'appartement à Lyon et sa région prend en charge le vidage complet ou partiel de tout type d'appartement. Du studio au T5, nos équipes interviennent avec rapidité et professionnalisme. Nous trions, évacuons et recyclons tous vos encombrants : meubles, électroménager, vêtements, bibelots. Chaque objet récupérable est orienté vers le don ou la revente.",
                'image'             => '/storage/sub-services/cmsAmNIMFZDfA2wR8UUgtRDej1BkNKYY1zBbKEVF.jpg',
                'features'          => '["Vidage complet studio à T5", "Tri et recyclage sur place", "Évacuation encombrants", "Nettoyage après débarras", "Devis gratuit sous 2h", "Équipe expérimentée"]',
                'content_blocks'    => '[{"title": "Un vidage adapté à votre logement", "text": "Que vous habitiez un studio ou un grand appartement, nous adaptons notre intervention à la taille et à la configuration de votre logement."}, {"title": "Tri et valorisation", "text": "Avant l\'évacuation, tri minutieux. Les objets de valeur sont identifiés, les objets en bon état orientés vers le don ou la revente, les matériaux recyclables séparés."}, {"title": "Remise en état", "text": "Après le vidage, nettoyage complet possible. Particulièrement apprécié dans le cadre de ventes immobilières."}]',
                'sort_order'        => 1,
                'is_active'         => true,
                'created_at'        => '2026-04-11 00:38:47',
                'updated_at'        => '2026-04-29 15:26:20',
            ],
            [
                'id'                => 2,
                'service_id'        => 1,
                'slug'              => 'debarras-rapide-devis-gratuit',
                'name'              => 'Débarras Rapide & Devis Gratuit',
                'icon'              => '📦',
                'short_description' => "Besoin d'un débarras urgent ? Nous intervenons sous 24h avec un devis gratuit et sans engagement.",
                'description'       => "Vous avez besoin d'un débarras en urgence ? 3D Services intervient sous 24h à Lyon et dans un rayon de 200 km. Notre processus est simple : vous nous appelez, nous établissons un devis gratuit en 2h, et nous intervenons dès validation. Pas de surprise, pas de frais cachés.",
                'image'             => '/storage/sub-services/650SZXu2xNvcg77Fo29PWOXiTfYrcxpKwAps0FST.jpg',
                'features'          => '["Intervention sous 24h", "Devis gratuit en 2h", "Sans engagement", "7j/7 y compris week-end", "Tarif transparent", "Équipe expérimentée"]',
                'content_blocks'    => '[{"title": "Un processus simple et rapide", "text": "Appelez-nous, décrivez votre besoin. En 2 heures, vous recevez un devis clair et détaillé. Dès validation, notre équipe intervient — souvent dès le lendemain."}, {"title": "Transparence totale", "text": "Nos tarifs sont affichés à l\'avance. Aucun frais caché, aucune surprise à la fin du chantier. Le prix annoncé est le prix facturé."}]',
                'sort_order'        => 2,
                'is_active'         => true,
                'created_at'        => '2026-04-29 15:28:20',
                'updated_at'        => '2026-04-29 15:28:20',
            ],
            [
                'id'                => 3,
                'service_id'        => 1,
                'slug'              => 'enlevement-encombrants',
                'name'              => 'Enlèvement Encombrants',
                'icon'              => '📦',
                'short_description' => "Évacuation de vos encombrants : meubles, électroménager, matelas. Service éco-responsable avec recyclage.",
                'description'       => "Notre service d'enlèvement d'encombrants prend en charge tous vos objets volumineux : meubles, matelas, canapés, électroménager, appareils électroniques. Nous assurons le tri sélectif et le recyclage de chaque matériau. Les objets en bon état sont donnés à des associations partenaires.",
                'image'             => '/storage/sub-services/t2RNam3U2YCAON9vyoSOkI94DAwNqhSQ7qznrdZz.jpg',
                'features'          => '["Meubles et canapés", "Électroménager", "Matelas et literie", "Appareils électroniques", "Recyclage éco-responsable", "Devis gratuit"]',
                'content_blocks'    => '[{"title": "Tous types d\'encombrants pris en charge", "text": "Canapés, armoires, réfrigérateurs, machines à laver, matelas — nous prenons en charge tous les objets volumineux que vous ne pouvez pas évacuer seul."}, {"title": "Une démarche éco-responsable", "text": "Chaque objet est trié : don aux associations pour les objets en état, recyclage des matériaux, déchèterie agréée pour le reste. Rien ne finit inutilement en décharge."}]',
                'sort_order'        => 3,
                'is_active'         => true,
                'created_at'        => '2026-04-29 15:29:04',
                'updated_at'        => '2026-04-29 15:30:01',
            ],
            [
                'id'                => 4,
                'service_id'        => 1,
                'slug'              => 'vide-maison',
                'name'              => 'Vide Maison',
                'icon'              => '📦',
                'short_description' => "Service complet de vide-maison : tri, évacuation, nettoyage. Idéal pour succession, déménagement ou libération de bien.",
                'description'       => "Le vide maison est un service complet qui consiste à vider entièrement une maison, du sous-sol au grenier. Que ce soit suite à une succession, une vente immobilière ou un déménagement, 3D Services prend en charge l'intégralité du processus.",
                'image'             => '/storage/sub-services/fVaj0mFiixpQnO5WfddFDayfOsFFkfqqXiW1cdoq.jpg',
                'features'          => '["Vidage complet cave au grenier", "Tri et valorisation des objets", "Nettoyage après vidage possible", "Idéal pour succession ou vente", "Devis gratuit sur place", "Équipe expérimentée"]',
                'content_blocks'    => '[{"title": "Un vidage complet de A à Z", "text": "Nous vidons chaque pièce : chambres, salon, cuisine, salle de bain, cave, grenier, garage et dépendances. Mobilier, électroménager, vêtements, vaisselle, objets divers — tout est pris en charge."}, {"title": "Tri et valorisation", "text": "Avant l\'évacuation, tri minutieux. Les objets de valeur sont identifiés, les objets en bon état orientés vers le don ou la revente, les matériaux recyclables séparés."}, {"title": "Remise en état", "text": "Après le vidage, nettoyage complet possible. Particulièrement apprécié dans le cadre de ventes immobilières."}]',
                'sort_order'        => 4,
                'is_active'         => true,
                'created_at'        => '2026-04-29 15:31:20',
                'updated_at'        => '2026-04-29 15:31:20',
            ],
            [
                'id'                => 5,
                'service_id'        => 1,
                'slug'              => 'debarras-succession',
                'name'              => 'Débarras Succession',
                'icon'              => '📦',
                'short_description' => "Prise en charge complète après un décès : tri respectueux des affaires, don aux associations, évacuation.",
                'description'       => "Le débarras succession demande tact et professionnalisme. Nos équipes interviennent avec respect et discrétion pour trier les affaires du défunt. Les objets de valeur sont inventoriés, les souvenirs mis de côté selon vos souhaits, et le reste est évacué proprement.",
                'image'             => '/storage/sub-services/ta4td7JpbpdM8GFnWdkF9fQz3ecglN0SCITOCCcY.jpg',
                'features'          => '["Tri respectueux", "Inventaire objets de valeur", "Don aux associations", "Évacuation complète", "Accompagnement personnalisé", "Discrétion assurée"]',
                'content_blocks'    => '[{"title": "Un accompagnement humain et discret", "text": "Nous comprenons la difficulté émotionnelle d\'un débarras après un décès. Nos équipes sont formées pour intervenir avec tact, respect et discrétion."}, {"title": "Inventaire et tri soigneux", "text": "Les objets de valeur sont identifiés et inventoriés. Les souvenirs personnels sont mis de côté. Les objets en bon état sont orientés vers le don aux associations."}]',
                'sort_order'        => 5,
                'is_active'         => true,
                'created_at'        => '2026-04-29 15:32:56',
                'updated_at'        => '2026-04-29 15:32:56',
            ],
            [
                'id'                => 6,
                'service_id'        => 1,
                'slug'              => 'debarras-cave',
                'name'              => 'Débarras Cave',
                'icon'              => '📦',
                'short_description' => "Vidage de cave encombrée : meubles, cartons, archives. Accès difficile ? Nos équipes sont équipées.",
                'description'       => "Les caves sont souvent des espaces oubliés qui s'encombrent au fil des années. Nos équipes sont spécialement équipées pour intervenir dans les accès difficiles : escaliers étroits, sous-sols humides, caves profondes. Nous évacuons tout type d'objet stocké.",
                'image'             => '/storage/sub-services/Gjp0dh9dPT2opVk5YMLbAGXMsEqVDSYbhQQ86ONL.jpg',
                'features'          => '["Accès difficile maîtrisé", "Meubles et cartons", "Archives et papiers", "Matériaux divers", "Nettoyage cave inclus", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 6,
                'is_active'         => true,
                'created_at'        => '2026-04-29 15:34:21',
                'updated_at'        => '2026-04-29 15:34:21',
            ],
            [
                'id'                => 7,
                'service_id'        => 1,
                'slug'              => 'debarras-grenier',
                'name'              => 'Débarras Grenier',
                'icon'              => '📦',
                'short_description' => "Nettoyage et vidage de grenier : objets anciens, archives, mobilier. Tri et recyclage inclus.",
                'description'       => "Le débarras de grenier nécessite une attention particulière aux objets anciens qui peuvent avoir de la valeur. Nos équipes trient soigneusement chaque objet, identifient les pièces de valeur et évacuent le reste de manière éco-responsable.",
                'image'             => '/storage/sub-services/zXHRRFxB4OcIJ6yj2VwxyqHMRdHFvXdXKHWIjhRL.jpg',
                'features'          => '["Tri objets anciens", "Identification pièces de valeur", "Évacuation sécurisée", "Recyclage inclus", "Accès combles et toitures", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 7,
                'is_active'         => true,
                'created_at'        => '2026-04-29 15:35:44',
                'updated_at'        => '2026-04-29 15:35:44',
            ],
            [
                'id'                => 8,
                'service_id'        => 1,
                'slug'              => 'debarras-jardin',
                'name'              => 'Débarras Jardin',
                'icon'              => '📦',
                'short_description' => "Évacuation des déchets verts, mobilier de jardin, gravats légers. Remise en état de votre extérieur.",
                'description'       => "Notre service de débarras jardin prend en charge l'évacuation de tous vos déchets extérieurs : mobilier de jardin usagé, déchets verts, gravats légers, outils hors d'usage. Nous remettons votre espace extérieur en état.",
                'image'             => '/storage/sub-services/rlsZnRbboDLCGkxs81LhYnSbfPBtiA4px6CAUI8u.jpg',
                'features'          => '["Déchets verts", "Mobilier de jardin", "Gravats légers", "Outils et équipements", "Remise en état terrain", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 8,
                'is_active'         => true,
                'created_at'        => '2026-04-29 15:36:37',
                'updated_at'        => '2026-04-29 15:36:37',
            ],
            [
                'id'                => 9,
                'service_id'        => 1,
                'slug'              => 'debarras-box-garage',
                'name'              => 'Débarras Box & Garage',
                'icon'              => '📦',
                'short_description' => "Vidage complet de box de stockage, garage ou cave. Intervention rapide même en accès difficile.",
                'description'       => "Box de stockage saturé ? Garage encombré ? Nous intervenons rapidement pour vider complètement votre espace. Nos équipes sont habituées aux contraintes d'accès des parkings souterrains et des zones de stockage.",
                'image'             => '/storage/sub-services/l93zuKTaIbHV9EFSgeX1DS2xrxeygJ6nHsRRumEj.jpg',
                'features'          => '["Box de stockage", "Garage et parking", "Accès souterrain", "Tri et recyclage", "Intervention rapide", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 9,
                'is_active'         => true,
                'created_at'        => '2026-04-29 15:37:35',
                'updated_at'        => '2026-04-29 15:37:35',
            ],
            [
                'id'                => 10,
                'service_id'        => 1,
                'slug'              => 'sos-debarras',
                'name'              => 'SOS Débarras',
                'icon'              => '📦',
                'short_description' => "Intervention d'urgence 7j/7 pour débarras immédiat. Expulsion, sinistre, insalubrité — nous répondons en 2h.",
                'description'       => "En cas d'urgence — expulsion locative, sinistre, insalubrité — notre service SOS Débarras intervient dans les plus brefs délais. Disponible 7j/7, nous garantissons une réponse sous 2h et une intervention sous 24h.",
                'image'             => '/storage/sub-services/KxMmFERw0cVecpMt63PGtWGNgBDAjAqy95BwRRe7.jpg',
                'features'          => '["Urgence 7j/7", "Réponse sous 2h", "Expulsion locative", "Sinistre et dégâts", "Insalubrité", "Intervention immédiate"]',
                'content_blocks'    => null,
                'sort_order'        => 10,
                'is_active'         => true,
                'created_at'        => '2026-04-29 15:38:52',
                'updated_at'        => '2026-04-29 15:38:52',
            ],
            [
                'id'                => 11,
                'service_id'        => 1,
                'slug'              => 'debarras-archives-entreprises',
                'name'              => 'Débarras Archives Entreprises',
                'icon'              => '📦',
                'short_description' => "Enlèvement et destruction sécurisée d'archives professionnelles. Confidentialité garantie.",
                'description'       => "Nous proposons un service de débarras et destruction sécurisée d'archives pour les entreprises. Confidentialité totale garantie avec certificat de destruction. Nous intervenons dans vos locaux professionnels à Lyon et sa région.",
                'image'             => '/storage/sub-services/EhO3jQ7OhnQ2AdyZl31Svop8TmWhYynQgqYfpIhl.jpg',
                'features'          => '["Destruction sécurisée", "Certificat de destruction", "Confidentialité garantie", "Intervention en entreprise", "Conformité RGPD", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-04-29 15:39:53',
                'updated_at'        => '2026-04-29 15:39:53',
            ],
            [
                'id'                => 12,
                'service_id'        => 1,
                'slug'              => 'entreprise-de-debarras',
                'name'              => 'Entreprise de Débarras',
                'icon'              => '📦',
                'short_description' => "3D Services, votre partenaire de confiance pour tous vos besoins de débarras à Lyon et sa région.",
                'description'       => "3D Services est votre entreprise de débarras de référence à Lyon et dans un rayon de 200 km. Forts de notre expérience, nous proposons des solutions sur mesure pour particuliers et professionnels. Devis gratuit, intervention rapide, tarifs compétitifs.",
                'image'             => '/storage/sub-services/kq5WpXwxfNPSWP1pKFwN8NBSd1Sj7CrLhTBjCl8N.jpg',
                'features'          => '["Particuliers et professionnels", "Devis gratuit sous 2h", "Intervention 7j/7", "Tarifs compétitifs", "Éco-responsable", "Équipe expérimentée"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-04-29 15:40:59',
                'updated_at'        => '2026-04-29 15:40:59',
            ],

            // ──────────────────────────────────────────────────────────────────
            // Service 2 — Démolition
            // ──────────────────────────────────────────────────────────────────

            [
                'id'                => 14,
                'service_id'        => 2,
                'slug'              => 'demolition-cloisons',
                'name'              => 'Démolition Cloisons',
                'icon'              => '📦',
                'short_description' => "Abattage de cloisons et murs non porteurs pour ouvrir vos espaces. Évacuation gravats incluse.",
                'description'       => "Notre service de démolition de cloisons permet de repenser l'agencement de votre intérieur. Nous abattons les murs non porteurs en toute sécurité, avec évacuation immédiate des gravats. Nos équipes vérifient systématiquement la nature du mur avant intervention.",
                'image'             => '/storage/sub-services/2e92EYAopM1Uv5sA9vTejUDMDsbcJRg6svuTx2OZ.jpg',
                'features'          => '["Cloisons en placo", "Cloisons en briques", "Vérification structure", "Évacuation gravats", "Nettoyage chantier", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 10:47:30',
                'updated_at'        => '2026-05-04 10:47:30',
            ],
            [
                'id'                => 15,
                'service_id'        => 2,
                'slug'              => 'depose-faux-plafonds',
                'name'              => 'Dépose Faux-Plafonds',
                'icon'              => '📦',
                'short_description' => "Retrait de faux-plafonds suspendus ou en plaques. Remise à nu pour rénovation.",
                'description'       => "La dépose de faux-plafonds est une étape clé de nombreux projets de rénovation. Nos équipes retirent tous types de faux-plafonds : suspendus, en dalles, en plaques de plâtre. L'évacuation des matériaux et le nettoyage sont systématiquement inclus.",
                'image'             => '/storage/sub-services/WJiWGhyNc4wEDzWtw6KiwfjOaeJNKR7imPGZKqem.jpg',
                'features'          => '["Faux-plafonds suspendus", "Dalles et plaques", "Isolation associée", "Évacuation matériaux", "Remise à nu complète", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 10:48:42',
                'updated_at'        => '2026-05-04 10:48:42',
            ],
            [
                'id'                => 16,
                'service_id'        => 2,
                'slug'              => 'retrait-carrelage-parquet',
                'name'              => 'Retrait Carrelage & Parquet',
                'icon'              => '📦',
                'short_description' => "Dépose de revêtements de sol : carrelage, parquet, moquette. Préparation pour nouveau revêtement.",
                'description'       => "Nous assurons la dépose complète de tous types de revêtements de sol : carrelage, faïence, parquet massif ou flottant, moquette, lino. Le support est nettoyé et préparé pour recevoir le nouveau revêtement.",
                'image'             => '/storage/sub-services/Hdr8mZgtwSzBNnIXe4QIsjWkuYa2MHiATnF4UPyE.jpg',
                'features'          => '["Carrelage et faïence", "Parquet massif et flottant", "Moquette et lino", "Préparation support", "Évacuation déchets", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 10:49:38',
                'updated_at'        => '2026-05-04 10:49:38',
            ],
            [
                'id'                => 17,
                'service_id'        => 2,
                'slug'              => 'demolition-cuisine',
                'name'              => 'Démolition Cuisine',
                'icon'              => '📦',
                'short_description' => "Dépose complète de cuisine équipée : meubles, plan de travail, crédence, électroménager encastré.",
                'description'       => "La démolition de cuisine comprend le retrait complet de tous les éléments : meubles hauts et bas, plan de travail, crédence, électroménager encastré. Nous déconnectons les arrivées d'eau et d'électricité en toute sécurité.",
                'image'             => '/storage/sub-services/Q8bXtWitXzJ9gPMmJt98CMwzRReeiPnlrxGEwHvX.jpg',
                'features'          => '["Meubles hauts et bas", "Plan de travail", "Crédence et faïence", "Électroménager encastré", "Déconnexion eau/élec", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 10:50:43',
                'updated_at'        => '2026-05-04 10:50:43',
            ],
            [
                'id'                => 18,
                'service_id'        => 2,
                'slug'              => 'demolition-salle-de-bain',
                'name'              => 'Démolition Salle de Bain',
                'icon'              => '📦',
                'short_description' => "Dépose complète de salle de bain : baignoire, douche, lavabo, carrelage mural et sol.",
                'description'       => "Nous réalisons la démolition complète de votre salle de bain pour préparer votre projet de rénovation. Baignoire, douche, lavabo, WC, carrelage mural et sol — tout est retiré proprement avec évacuation des gravats.",
                'image'             => '/storage/sub-services/yHNiHnGbXBoN99GBCCR4Vza1fYTmprq8lS6yPkhS.jpg',
                'features'          => '["Baignoire et douche", "Lavabo et WC", "Carrelage mural", "Carrelage sol", "Plomberie sécurisée", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 10:51:51',
                'updated_at'        => '2026-05-04 10:51:51',
            ],
            [
                'id'                => 19,
                'service_id'        => 2,
                'slug'              => 'evacuation-gravats',
                'name'              => 'Évacuation Gravats',
                'icon'              => '📦',
                'short_description' => "Évacuation de tous types de gravats en benne. Tri et recyclage des matériaux de démolition.",
                'description'       => "L'évacuation des gravats est un service essentiel après toute démolition. Nous mettons à disposition des bennes adaptées et assurons le transport vers les centres de tri et recyclage agréés. Béton, plâtre, brique, bois — tout est pris en charge.",
                'image'             => '/storage/sub-services/d41nIRXCLV7ttg8JO9dD0iFitqSGdMRynGLijV37.jpg',
                'features'          => '["Benne sur place", "Béton et plâtre", "Brique et pierre", "Bois et métaux", "Centre de tri agréé", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 10:53:00',
                'updated_at'        => '2026-05-04 10:53:00',
            ],
            [
                'id'                => 20,
                'service_id'        => 2,
                'slug'              => 'demolition-interieure-complete',
                'name'              => 'Démolition Intérieure Complète',
                'icon'              => '📦',
                'short_description' => "Déconstruction totale de l'intérieur d'un local : idéal pour rénovation lourde ou changement d'usage.",
                'description'       => "Pour les projets de rénovation lourde, nous réalisons la démolition intérieure complète : toutes les cloisons, revêtements, faux-plafonds, installations sanitaires et électriques sont retirés. Le local est remis à nu, prêt pour la reconstruction.",
                'image'             => '/storage/sub-services/zQyzgea8oOXfXpZU0CxIZlaO5OBK9WjTRlE7McP6.jpg',
                'features'          => '["Mise à nu complète", "Cloisons et doublages", "Installations sanitaires", "Installations électriques", "Local prêt à rénover", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 10:54:02',
                'updated_at'        => '2026-05-04 10:54:02',
            ],
            [
                'id'                => 21,
                'service_id'        => 2,
                'slug'              => 'demolition-bureaux-commerces',
                'name'              => 'Démolition Bureaux & Commerces',
                'icon'              => '📦',
                'short_description' => "Déconstruction de bureaux et locaux commerciaux. Intervention planifiée hors horaires d'activité.",
                'description'       => "Nous intervenons dans les bureaux et locaux commerciaux pour tous vos besoins de démolition. Nos interventions sont planifiées hors horaires d'activité pour minimiser les perturbations. Nous respectons les normes de sécurité et les contraintes spécifiques des ERP.",
                'image'             => '/storage/sub-services/lVEe3JFsxggnE1ht7wdbsCAIuBX0LsNVTOIrqE26.jpg',
                'features'          => '["Intervention hors horaires", "Cloisons de bureaux", "Faux-planchers", "Aménagements commerciaux", "Respect normes ERP", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 10:55:02',
                'updated_at'        => '2026-05-04 10:55:02',
            ],

            // ──────────────────────────────────────────────────────────────────
            // Service 3 — Amiante
            // ──────────────────────────────────────────────────────────────────

            [
                'id'                => 13,
                'service_id'        => 3,
                'slug'              => 'diagnostic-amiante',
                'name'              => 'Diagnostic Amiante',
                'icon'              => '📦',
                'short_description' => "Diagnostic amiante avant travaux ou avant vente. Rapport certifié conforme à la réglementation.",
                'description'       => "Le diagnostic amiante est obligatoire avant tous travaux dans les bâtiments construits avant 1997. Nos techniciens certifiés réalisent les prélèvements et analyses nécessaires. Un rapport détaillé vous est remis avec les préconisations adaptées.",
                'image'             => '/storage/sub-services/tfsneULLEatzpsdCK0QYOZDWLjwXxtliHuA9CjDi.jpg',
                'features'          => '["Prélèvements certifiés", "Analyse en laboratoire", "Rapport réglementaire", "Avant travaux / avant vente", "Préconisations adaptées", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 1,
                'is_active'         => true,
                'created_at'        => '2026-04-29 15:42:16',
                'updated_at'        => '2026-04-29 15:42:16',
            ],
            [
                'id'                => 22,
                'service_id'        => 3,
                'slug'              => 'retrait-plaques-fibrociment',
                'name'              => 'Retrait Plaques Fibrociment',
                'icon'              => '📦',
                'short_description' => "Dépose sécurisée de plaques de fibrociment amiantées : toitures, bardages, conduits.",
                'description'       => "Les plaques de fibrociment contenant de l'amiante sont présentes dans de nombreux bâtiments. Nos équipes certifiées assurent leur retrait en toute sécurité, avec confinement de la zone et évacuation vers des centres agréés.",
                'image'             => '/storage/sub-services/X9FWeQKa2FE1fJT602dn73Y6heqjS0sEtychYHyM.jpg',
                'features'          => '["Toitures fibrociment", "Bardages amiantés", "Conduits et gaines", "Confinement zone", "Évacuation centre agréé", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 10:57:47',
                'updated_at'        => '2026-05-04 10:57:47',
            ],
            [
                'id'                => 23,
                'service_id'        => 3,
                'slug'              => 'retrait-dalles-amiantees',
                'name'              => 'Retrait Dalles Amiantées',
                'icon'              => '📦',
                'short_description' => "Dépose de dalles de sol contenant de l'amiante. Intervention sécurisée et traçabilité complète.",
                'description'       => "Les dalles de sol vinyle-amiante sont très courantes dans les bâtiments des années 60 à 80. Nous assurons leur retrait en suivant un protocole strict de sécurité, avec traçabilité complète des déchets.",
                'image'             => '/storage/sub-services/AjxrnowXeaq9ctkQzu4G32TZUW5y5wNt0DNEHMAf.jpg',
                'features'          => '["Dalles vinyle-amiante", "Protocole sécurisé", "Traçabilité déchets", "Bordereau de suivi", "Remise en état sol", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 10:58:44',
                'updated_at'        => '2026-05-04 10:58:44',
            ],
            [
                'id'                => 24,
                'service_id'        => 3,
                'slug'              => 'retrait-flocage-amiante',
                'name'              => 'Retrait Flocage Amiante',
                'icon'              => '📦',
                'short_description' => "Déflocage de matériaux amiantés : plafonds, poutres, canalisations. Zone confinée et sécurisée.",
                'description'       => "Le flocage amiante est la forme la plus dangereuse car les fibres se libèrent facilement. Nos équipes interviennent en zone confinée avec des équipements de protection respiratoire adaptés. Chaque chantier fait l'objet d'un plan de retrait validé.",
                'image'             => '/storage/sub-services/WCJL42eG79BwvlKExRiMUtbCF70Bb8kf7RBlpfC8.jpg',
                'features'          => '["Plafonds et poutres", "Canalisations", "Zone confinée hermétique", "Protection respiratoire", "Mesures d\'empoussièrement", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 10:59:48',
                'updated_at'        => '2026-05-04 10:59:48',
            ],
            [
                'id'                => 25,
                'service_id'        => 3,
                'slug'              => 'confinement-securisation',
                'name'              => 'Confinement & Sécurisation',
                'icon'              => '📦',
                'short_description' => "Mise en place de zones de confinement pour chantiers de désamiantage. Respect des normes SS3/SS4.",
                'description'       => "La sécurisation d'un chantier de désamiantage passe par la mise en place d'un confinement hermétique. Nos équipes installent des sas d'entrée/sortie, des extracteurs d'air avec filtration HEPA, et réalisent les tests d'étanchéité réglementaires.",
                'image'             => '/storage/sub-services/SFyBkvTe34zm5IfzmJEffEj9fVzPSwVZ9WG3drcR.jpg',
                'features'          => '["Confinement hermétique", "Sas personnel/matériel", "Filtration HEPA", "Tests d\'étanchéité", "Normes SS3/SS4", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:01:06',
                'updated_at'        => '2026-05-04 11:01:06',
            ],
            [
                'id'                => 26,
                'service_id'        => 3,
                'slug'              => 'evacuation-dechets-amiantes',
                'name'              => 'Évacuation Déchets Amiantés',
                'icon'              => '📦',
                'short_description' => "Transport et élimination des déchets amiantés en centre agréé. Bordereau de suivi des déchets.",
                'description'       => "L'évacuation des déchets amiantés est strictement réglementée. Nous assurons le conditionnement, le transport et l'élimination en Installation de Stockage de Déchets Dangereux (ISDD). Un bordereau de suivi des déchets (BSD) vous est remis.",
                'image'             => '/storage/sub-services/AEwrEie9S79Nsi36p36uI3eXvwlYq1UueSorwEmL.jpg',
                'features'          => '["Conditionnement réglementaire", "Transport sécurisé", "Centre ISDD agréé", "Bordereau BSD", "Certificat d\'élimination", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:02:35',
                'updated_at'        => '2026-05-04 11:02:35',
            ],

            // ──────────────────────────────────────────────────────────────────
            // Service 4 — Nettoyage
            // ──────────────────────────────────────────────────────────────────

            [
                'id'                => 27,
                'service_id'        => 4,
                'slug'              => 'nettoyage-locaux-apres-debarras',
                'name'              => 'Nettoyage Locaux après Débarras',
                'icon'              => '📦',
                'short_description' => "Remise en état complète de vos locaux après un débarras. Sol, murs, vitres — tout est nettoyé.",
                'description'       => "Après un débarras, vos locaux nécessitent un nettoyage en profondeur. Nos équipes interviennent immédiatement pour remettre en état sols, murs, vitres et sanitaires. Résultat impeccable garanti.",
                'image'             => '/storage/sub-services/4W54b11larq4a3bKZYqF54uejO8vOTiWNZE3Lihr.jpg',
                'features'          => '["Sols et murs", "Vitres et menuiseries", "Sanitaires", "Désodorisation", "Prêt à habiter", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:05:44',
                'updated_at'        => '2026-05-04 11:05:44',
            ],
            [
                'id'                => 28,
                'service_id'        => 4,
                'slug'              => 'entreprise-de-nettoyage',
                'name'              => 'Entreprise de Nettoyage',
                'icon'              => '📦',
                'short_description' => "3D Services, entreprise de nettoyage professionnel à Lyon. Particuliers et professionnels.",
                'description'       => "3D Services est votre entreprise de nettoyage de confiance à Lyon et dans un rayon de 200 km. Nous proposons une gamme complète de services de nettoyage pour particuliers et professionnels.",
                'image'             => '/storage/sub-services/lVdp4FYbFjKME6ao8PVspDu4vWQ4Oweyo22wOWHw.jpg',
                'features'          => '["Particuliers et pros", "Intervention 7j/7", "Équipements pro", "Produits certifiés", "Équipe expérimentée", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:07:00',
                'updated_at'        => '2026-05-04 11:07:00',
            ],
            [
                'id'                => 29,
                'service_id'        => 4,
                'slug'              => 'nettoyage-bureaux',
                'name'              => 'Nettoyage Bureaux',
                'icon'              => '📦',
                'short_description' => "Entretien régulier ou ponctuel de vos bureaux et espaces de travail. Résultat impeccable garanti.",
                'description'       => "Un environnement de travail propre améliore la productivité. Nous proposons des contrats d'entretien régulier ou des interventions ponctuelles pour vos bureaux, salles de réunion, espaces communs et sanitaires.",
                'image'             => '/storage/sub-services/iDu6lE154haS4mUsVIuPR5cSUQ1xuWYRZ7uGUeJp.jpg',
                'features'          => '["Entretien régulier", "Intervention ponctuelle", "Sols et surfaces", "Sanitaires", "Espaces communs", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:08:11',
                'updated_at'        => '2026-05-04 11:08:11',
            ],
            [
                'id'                => 30,
                'service_id'        => 4,
                'slug'              => 'nettoyage-appartement',
                'name'              => 'Nettoyage Appartement',
                'icon'              => '📦',
                'short_description' => "Nettoyage complet de votre appartement : sols, vitres, cuisine, salle de bain. Produits professionnels.",
                'description'       => "Notre service de nettoyage d'appartement couvre chaque pièce de votre logement. Cuisine, salle de bain, chambres, salon — nous utilisons des produits professionnels pour un résultat impeccable. Idéal pour un état des lieux ou un grand ménage.",
                'image'             => '/storage/sub-services/kFXcB4b8bZZrHwdfDwHWmKrcHrPAUB5rzkQ9bM3F.jpg',
                'features'          => '["Cuisine complète", "Salle de bain", "Sols et parquets", "Vitres intérieures", "État des lieux", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:09:10',
                'updated_at'        => '2026-05-04 11:09:10',
            ],
            [
                'id'                => 31,
                'service_id'        => 4,
                'slug'              => 'nettoyage-fin-de-chantier',
                'name'              => 'Nettoyage Fin de Chantier',
                'icon'              => '📦',
                'short_description' => "Remise en état après travaux : poussière, résidus de peinture, gravats légers. Prêt à emménager.",
                'description'       => "Le nettoyage de fin de chantier est indispensable après des travaux de rénovation. Nos équipes éliminent poussière de plâtre, résidus de peinture, traces de colle et gravats légers. Votre espace est prêt à être aménagé.",
                'image'             => '/storage/sub-services/puqAYTzmjqMzUrS7QdYvFdfXz7wz9ZSou2uiFdqQ.jpg',
                'features'          => '["Poussière de plâtre", "Résidus de peinture", "Traces de colle", "Gravats légers", "Aspirations et lavage", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:10:14',
                'updated_at'        => '2026-05-04 11:10:14',
            ],
            [
                'id'                => 32,
                'service_id'        => 4,
                'slug'              => 'nettoyage-industriel',
                'name'              => 'Nettoyage Industriel',
                'icon'              => '📦',
                'short_description' => "Nettoyage de sites industriels, entrepôts, usines. Équipements professionnels et personnel qualifié.",
                'description'       => "Nous intervenons sur les sites industriels avec des équipements adaptés : autolaveuses, aspirateurs industriels, nettoyeurs haute pression. Entrepôts, usines, ateliers — nos équipes sont formées aux contraintes spécifiques de chaque environnement.",
                'image'             => '/storage/sub-services/llbrHvcG11Yb8smrPNUGNTo0M9eVGVIThzsCgAOS.jpg',
                'features'          => '["Entrepôts et usines", "Autolaveuse", "Aspirateur industriel", "Haute pression", "Protocole sécurité", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:11:10',
                'updated_at'        => '2026-05-04 11:11:10',
            ],
            [
                'id'                => 33,
                'service_id'        => 4,
                'slug'              => 'lavage-nettoyage-vitres',
                'name'              => 'Lavage & Nettoyage Vitres',
                'icon'              => '📦',
                'short_description' => "Nettoyage de vitres intérieures et extérieures, en hauteur ou accès difficile. Résultat sans traces.",
                'description'       => "Nos vitriers professionnels interviennent pour le nettoyage de toutes vos surfaces vitrées : vitrines, baies vitrées, vérandas, verrières. Nous travaillons en hauteur avec des équipements adaptés pour un résultat sans traces.",
                'image'             => '/storage/sub-services/17Cis1Fh8msmEsOoP6Qi0LmmmbKLXHlSRQKvDYqw.jpg',
                'features'          => '["Vitrines commerciales", "Baies vitrées", "Vérandas", "Travail en hauteur", "Résultat sans traces", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:12:45',
                'updated_at'        => '2026-05-04 11:12:45',
            ],
            [
                'id'                => 34,
                'service_id'        => 4,
                'slug'              => 'nettoyage-restaurant',
                'name'              => 'Nettoyage Restaurant',
                'icon'              => '📦',
                'short_description' => "Nettoyage professionnel de restaurants et cuisines. Respect des normes d'hygiène HACCP.",
                'description'       => "Le nettoyage de restaurant exige le respect strict des normes d'hygiène HACCP. Nos équipes nettoient cuisines professionnelles, salles de restaurant, sanitaires et espaces de stockage avec des produits agréés alimentaire.",
                'image'             => '/storage/sub-services/Cn6juJtXgFrIXP93p2ddOWfK2IAGSz0geWutvloz.jpg',
                'features'          => '["Cuisine professionnelle", "Salle de restaurant", "Normes HACCP", "Produits agréés", "Hotte et extraction", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:13:57',
                'updated_at'        => '2026-05-04 11:13:57',
            ],
            [
                'id'                => 35,
                'service_id'        => 4,
                'slug'              => 'nettoyage-haute-pression',
                'name'              => 'Nettoyage Haute Pression',
                'icon'              => '📦',
                'short_description' => "Décapage et nettoyage haute pression : façades, terrasses, parkings, sols industriels.",
                'description'       => "Notre service de nettoyage haute pression élimine les salissures les plus tenaces : mousses, graffitis, taches d'huile, traces noires. Nous intervenons sur façades, terrasses, parkings, allées et sols industriels.",
                'image'             => '/storage/sub-services/deX2vZSPLYVVjm0uIDECjNo97tuqtoCfbo0czLFy.jpg',
                'features'          => '["Façades", "Terrasses et dalles", "Parkings", "Graffitis", "Sols industriels", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:14:59',
                'updated_at'        => '2026-05-04 11:14:59',
            ],
            [
                'id'                => 36,
                'service_id'        => 4,
                'slug'              => 'nettoyage-base-de-vie-chantier',
                'name'              => 'Nettoyage Base de Vie Chantier',
                'icon'              => '📦',
                'short_description' => "Entretien et nettoyage des bases de vie de chantier : bungalows, sanitaires, réfectoires.",
                'description'       => "L'entretien des bases de vie de chantier est essentiel pour le bien-être des équipes. Nous nettoyons bungalows, sanitaires chimiques, réfectoires et espaces communs selon un planning régulier ou à la demande.",
                'image'             => '/storage/sub-services/PAjEwN3iYQqAazxetsYT5t99pqFZxXrt4lceMRvS.jpg',
                'features'          => '["Bungalows", "Sanitaires", "Réfectoires", "Espaces communs", "Planning régulier", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:16:10',
                'updated_at'        => '2026-05-04 11:16:10',
            ],
            [
                'id'                => 37,
                'service_id'        => 4,
                'slug'              => 'nettoyage-apres-degats-des-eaux',
                'name'              => 'Nettoyage après Dégâts des Eaux',
                'icon'              => '📦',
                'short_description' => "Intervention rapide après sinistre : assèchement, désinfection, remise en état de votre local.",
                'description'       => "Après un dégât des eaux, une intervention rapide est cruciale. Nos équipes assurent le pompage, l'assèchement, la désinfection et la remise en état de vos locaux. Nous travaillons avec les assurances pour faciliter vos démarches.",
                'image'             => '/storage/sub-services/QnEi0DqU5BCsZIz91r19bNYCLX37pnDoloPwlpPF.jpg',
                'features'          => '["Pompage et aspiration", "Assèchement", "Désinfection", "Remise en état", "Dossier assurance", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:17:08',
                'updated_at'        => '2026-05-04 11:17:08',
            ],
            [
                'id'                => 38,
                'service_id'        => 4,
                'slug'              => 'nettoyage-syndrome-de-diogene',
                'name'              => 'Nettoyage Syndrome de Diogène',
                'icon'              => '📦',
                'short_description' => "Prise en charge des cas extrêmes avec discrétion et professionnalisme. Désinfection complète.",
                'description'       => "Le syndrome de Diogène nécessite une intervention spécialisée. Nos équipes interviennent avec discrétion et professionnalisme : débarras, nettoyage en profondeur, désinfection, traitement anti-nuisibles. Nous accompagnons les familles et les services sociaux.",
                'image'             => '/storage/sub-services/VoYAIQddUhlqLmvJKKVcdRQLgqcNfYG0K9bwowb2.jpg',
                'features'          => '["Débarras complet", "Nettoyage profondeur", "Désinfection totale", "Anti-nuisibles", "Accompagnement familles", "Devis gratuit"]',
                'content_blocks'    => null,
                'sort_order'        => 0,
                'is_active'         => true,
                'created_at'        => '2026-05-04 11:18:01',
                'updated_at'        => '2026-05-04 11:18:01',
            ],
        ];

        foreach ($subServices as $data) {
            SubService::create($data);
        }

        $this->command->info('✅ ' . count($subServices) . ' sous-services créés avec succès.');
    }
}
